version: 2

project_name: task-tui

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - id: task-tui
    binary: task-tui
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '6'
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -s -w -X main.commit={{.Commit}}
      - -s -w -X main.date={{.Date}}

archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - name: task-tui
    commit_author:
      name: aleksandersh
      email: alex-shuttle@yandex.ru
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/aleksandersh/task-tui/"
    description: "Terminal user interface for Task"
    license: "MIT"
    repository:
      owner: aleksandersh
      name: homebrew-task-tui
      branch: main
    test: |
      system "#{bin}/task-tui --version"
