version: "3"

includes:
  utils: UtilsTaskfile.yml
  docker: docker

tasks:
  etcd:connect:
    cmds:
      - etcd-tui localhost:2379 --user user1 --password password1
    preconditions:
      - etcd-tui --version
    desc: Connect to demo etcd cluster using etcd-tui
    summary: |
      Connect to demo etcd cluster using etcd-tui

  hello:
    label: Hello, Task!
    cmds:
      - "{{.TASKFILE_DIR}}/hello.sh"
    desc: An example of interactive script
    summary: |
      An example of interactive script
